### PR TITLE
Made node name setable. If not set, set to random uuid

### PR DESCRIPTION
**Pull request by hikhvar**

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
this is incomplete AFAICT. `node.name: ${NODE_NAME}` needs to be added to config/elasticsearch.yaml` in order for this to be effective.

**Comment by hikhvar** [comment]
You are correct. :thinking: Seems to be a git fuck up at my side. Here is a fix: https://github.com/pires/docker-elasticsearch/pull/29

**Comment by pires** [comment]
I will do something I don't usually do but this was my fault and so I need to make a proper fix. I will overwrite the 5.2.2 image version.

**Comment by pires** [comment]
Done.

**Comment by hikhvar** [comment]
Maybe, you can add a "Image-Version" to the Tag. Like:
```
docker-elasticsearch:5.2.2-1
docker-elasticsearch:5.2.2-2
```
Debian Packages and other Linux Packageformats use that semantic. This avoid updating already published Tags.

**Comment by pires** [comment]
I did that for other versions but I'm not doing it for this change. It's done!

**Pull request merged**
