### PR TITLE
Properly fixing #70

### PR DESCRIPTION
**Pull request by nick-pap**
This fixes the find command to properly scan only for files not having elasticsearch user in specific folders

### CODE REVIEW

**Comment by pires** [comment]
Hello @dn0! As the bug reporter, can you please review?

**Comment by dn0** [comment]
Btw. What is the motivation behind this?
I understand that before starting a fresh node it is needed.
But for restarts and upgrades I don't see the benefit.

Maybe we could go back to `chown -R`, but only when started for the first time, e.g.:
```bash
if [ ! -d /data/data/nodes ]; then
    chown -R elasticsearch:elasticsearch /data
fi
```

And the ownership of the `/elasticsearch` (`$BASE`) folder and subfolder could be handled in the Dockerfile during build time.

**Comment by pires** [comment]
@dn0 why don't you own a PR that addresses all of this properly? I'd like to include it as part of 6.4.2.

**Comment by dn0** [comment]
@pires @nick-pap https://github.com/pires/docker-elasticsearch/pull/75

**Pull request closed without merging**
