### PR TITLE
Set environment var for node.max_local_storage_nodes #23

### PR DESCRIPTION
**Pull request by vganapathy1**
Set environment var for node.max_local_storage_nodes #23

### CODE REVIEW

**Comment by pires** [comment]
Is it no longer possible to reuse an existing data folder?

**Comment by vganapathy1** [comment]
Unfortunately, yes that's what it appears to be!

**Comment by pires** [comment]
Can you add this variable to `README.md`, as well?

**Comment by vganapathy1** [comment]
README.md updated

**Comment by pires** [comment]
Thank you!

**Pull request merged**
